### ISSUE TITLE
How do I load image from Django uploaded image binary file and use face_recognition

### ISSUE THREAD

**Issue by axilaris** [ageitgey/face_recognition#324]
* face_recognition version:

face-recognition==1.0.0
face-recognition-models==0.3.0

* Python version: Python 3.6.3
* Operating System:
MacOS High Sierra 10.13.1 (eventually will run it on ubuntu production)

### Description

I think this applies to any web/rest based API.

I have a Django app that I want the user to upload the face image or pass it through web rest based API. The problem is how do I load this image ? In the current example is load_image_file("my_picture.jpg") but i believe this will take it from the file system.

How do I load an image that is uploaded binary (without saving it to the filesystem) ?

### What I Did

I have uploaded an image (jpg/png) through a browse button from Django web app just like this https://imgur.com/a/fVKuF

From the code I will obtain the face_image_obj object and then try to pass it the face_locations function. However the face_image_obj is not compatible. In the example, I believe load_image_file is from the file system, but with web based api, we are to get it from an uploaded source.

            **face_image_obj = employeefaceimageupload_form.cleaned_data["face_image"]
            logging.debug("face_image_obj type: %s" % type(face_image_obj))
            face_location_unknown = face_recognition.face_locations(face_image_obj)**

face_recognition will cause this exception:
**Exception Value: | Unsupported image type, must be 8bit gray or RGB image.**

i check the image type using this type(face_image_obj is 
**<class 'django.core.files.uploadedfile.InMemoryUploadedFile'>**

**Comment by ageitgey** [comment]
This is really a Django question. There's an example of how to do this with Flask (as opposed to Django) here: https://github.com/ageitgey/face_recognition/blob/master/examples/web_service_example.py

**Comment by axilaris** [comment]
Thank you very much. It worked. I just needed to pass the image object to load_image_file().

            face_image_obj = employeefaceimageupload_form.cleaned_data["face_image"]
            unknown_image = face_recognition.load_image_file(face_image_obj)

**Comment by ageitgey** [comment]
Thanks for posting the solution for the next person too!  :-)

**Comment by axilaris** [comment]
this now does not work on django 3.1 (I am doing a migration from 1.11 -> 3.1)

```
        face_image_obj = employeefaceimageupload_form.cleaned_data["face_image"]
        unknown_image = face_recognition.load_image_file(face_image_obj)
```

Can someone let me know what needs to fix to load_image_file from an uploaded face image file ?

The error as following
```
, in load_image_file
    return scipy.misc.imread(file, mode=mode)
AttributeError: module 'scipy.misc' has no attribute 'imread'

```

**Comment by axilaris** [comment]
updated this and solved the issue

face-recognition==1.3.0
scipy==1.6.2
